name: wisatabandung
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  #tambah assets images/
  assets:
    - images/ 

  #fonts
  fonts:
    - family: Staatliches
      fonts:
        - asset: fonts/Staatliches/Staatliches-Regular.ttf
    - family:  Oxygen
      fonts:
        - asset: fonts/Oxygen/Oxygen-Regular.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
